### ISSUE TITLE
Can't Upload

### ISSUE THREAD

**Issue by bittyrsweet** [I5UCC/VRC-ASL_Gestures#3]
When I go to the VRCSDK the build&publish for windows button is greyed out and it says I have too many parameters. When I tried installing the tool as well it gave me the warning "signs disabled parameter already exists". I'm very new to avatar creation, I apologize.

**Comment by I5UCC** [comment]
So, if the VRCSDK tells you, you have too many parameters and my tool still installed normally (you can ignore that warning), then you might not have the newest sdk installed in your project. The "too many parameters" error shows up when your avatars expression parameters exceed 256 points (with an old sdk that is 128). 

You can find your Expression parameters all the way at the bottom of your VRC Avatar Descriptor.
![image](https://user-images.githubusercontent.com/43730681/182396733-4a3bb5e8-0c43-456f-ba08-0044d7f10a4a.png)

When you open that file, at the bottom of it make sure it does not exceed 256, if it shows you have -/128 that means you need to update the newest VRC SDK
![image](https://user-images.githubusercontent.com/43730681/182396998-7f5e4d4c-291e-4561-b5f7-5d481b6b2d2b.png)

That might require you to remove some Parameters, so that means also features of your avatar, tho for the ASL hands to work you need to have these parameters still in that file.
If you need more assistance with this issue feel free to add my discord, I5UCC#6781
